#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd TripBuddy-Client
echo "eslint client..."
npm run format

cd ../TripBuddy-Server 
echo "eslint server..."
npm run format
echo "testing server..."
npm run test